# Generated by Django 5.2.9 on 2025-12-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes'),
        ),
    ]
